1er essai

diff --git a/srcs/front/Dockerfile b/srcs/front/Dockerfile
--- a/srcs/front/Dockerfile
+++ b/srcs/front/Dockerfile
@@ -20,6 +20,26 @@ COPY . .
 RUN npm run build
 
 #AJOUT DE TSX WATCH
+# Installation, initialisation et compilation du css avec tailwind
+RUN cd www && npx tailwindcss -i ./css/style.css -o ./css/output.css --minify
+
+# Vérification que output.css a bien été créé
+RUN test -f /app/www/css/output.css || (echo "ERROR: output.css not generated!" && exit 1)
+
+# A SUPPRIMER | Seulement pour le dev
+RUN apk add --no-cache npm inotify-tools
+RUN npm install -g typescript nodemon tailwindcss@3.4.18
+#####################################
+
+
+# A SUPPRIMER ##################################################
+# Copie du script de demarage pour le hot reload
+COPY conf/start_debug.sh /etc/nginx/html/conf/start_debug.sh
+COPY conf/watch-content.sh /etc/nginx/html/conf/watch-content.sh
+RUN chmod +x /etc/nginx/html/conf/start_debug.sh /etc/nginx/html/conf/watch-content.sh
+# CMD pour le dev 
+CMD ["/etc/nginx/html/conf/start_debug.sh"]
+# A SUPPRIMER ##################################################
 
 #-------------------------------------
 # STEP 2: STATIC SERVER WITH NGINX
